Add Labels (using Hashtag names from Gerrty)
hubtty/hubtty pull request #3
Opened 2020-11-22 23:02 UTC by EmilienM

This patch adds supports for labels in the changes, but it's limited
now (only view labels).
Also, we might need to rename the methods since Hashtag naming was good
for Gerrit but not for Github.

2020-11-28 00:04 UTC, EmilienM commented
wow

2020-12-05 09:03 UTC, mandre reviewed
Do you want to keep working on the labels feature in this branch, or do you instead want to merge as we go?

Things I'd like to see before calling this feature complete:
- [ ] retrieve possible labels for the project from github and store them in base
- [ ] add label should present a checkbox to the user with a list of possible labels
- [ ] possibly re-use the same color to display the label
- [ ] remove references to hashtags everywhere from the code and replace with labels. We'll need to rename the DB table. This will be a bit tricky because there's already a label table used for approvals I think.

2020-12-05 22:22 UTC, EmilienM commented
> Do you want to keep working on the labels feature in this branch, or do you instead want to merge as we go?

please don't merge, it's highly WIP now.

2020-12-05 22:23 UTC, EmilienM commented on hubtty/alembic/versions/399c4b3dcc9a_add_hashtags.py
> +    sa.Column('description', sa.String(length=255), index=True, nullable=False),
yeah i'll revert that change

2020-12-31 18:35 UTC, mandre requested changes
First review from hubtty \o/

2020-12-31 18:35 UTC, mandre commented on hubtty/sync.py
> +            sync.post('repos/%s/labels' % (change.id,),
This will have to be `change_id`.

2021-01-11 09:26 UTC, mandre reviewed
Testing review on own repo

2021-06-22 15:20 UTC, mandre commented
Closed in favor of #39

2021-06-22 15:20 UTC, closed without merging